### ISSUE TITLE
SQL AO on 2016 Standard Edition

### ISSUE THREAD

**Issue by chboeye** [MicrosoftDocs/SCCMDocs.fr-fr#4]
Any infirmation regarding the possiblity to do SQL AO with a standard edition of SQL 2016 ?
https://docs.microsoft.com/fr-fr/sql/database-engine/availability-groups/windows/basic-availability-groups-always-on-availability-groups?view=sql-server-2017
This article say the "Edition" must be "Enterprise", whatever the version.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 53d1da83-d988-fb2b-82c5-fd9cf117cd42
* Version Independent ID: 2b1a3bd2-5116-1f21-c196-e3e5698a83c9
* Content: [SQL Server AlwaysOn - Configuration Manager](https://docs.microsoft.com/fr-fr/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database)
* Content Source: [sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md](https://github.com/Microsoft/SCCMDocs.fr-fr/blob/live/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by srvbpigh** [comment]
Hello, @chboeye
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by aczechowski** [comment]
Hi @chboeye, thanks for the question. While SQL Server supports basic Always On availability groups with standard edition, Configuration Manager requires enterprise edition for how we use them. I suggest that you file [product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback). If you haven't already, add your vote to this [UserVoice idea](https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/34043482-add-support-for-hosting-the-configmgr-db-on-a-basi).
I suggest closing this issue as there's nothing actionable for docs at this time.
#please-close
