### ISSUE TITLE
Profil navigateur Edge et fichier PDF

### ISSUE THREAD

**Issue by VincentSTH** [MicrosoftDocs/SCCMDocs.fr-fr#5]
Bonjour,

Depuis, la mise en place de cette configuration "Définir Microsoft Edge comme navigateur par défaut" via SCCM, nous rencontrons le problème suivant :
* Les fichiers PDF s'ouvre par défaut dans Edge, et si les utilisateurs décident de modifier le paramétrage pour ouvrir les fichiers dans Acrobat Reader DC, le paramètre s'annule à chaque redémarrage du poste.

Nous avons supprimé la stratégie de conformité, mais le problème persiste.

Avez vous une solution à ce dysfonctionnement de SCCM ?
merci par avance pour votre retour
cdt
vincent
email : vincent.perron@sthubert.fr

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 0ee3d814-4441-b1b2-3e06-72e348b8ed84
* Version Independent ID: c3dbfe0f-d6ea-7357-7632-e5c609530bd6
* Content: [Configurer les paramètres Microsoft Edge - Configuration Manager](https://docs.microsoft.com/fr-fr/sccm/compliance/deploy-use/browser-profiles#feedback)
* Content Source: [sccm/compliance/deploy-use/browser-profiles.md](https://github.com/Microsoft/SCCMDocs.fr-fr/blob/live/sccm/compliance/deploy-use/browser-profiles.md)
* Product: **configuration-manager**
* Technology: **configmgr-compliance**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
#please-translate
Thanks @VincentSTH for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
#please-close

p.s. You can also file [Product Feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) to share the problem directly with the engineering team. However the support options above will provide you with the best level of service in investigating the issue.

**Comment by CeciAc** [comment]
Traduction provenant du commentaire ci-dessus 
Merci  @VincentSTH d'avoir pris le temps de partager cela avec l'équipe de  documentation de Configuration Manager. Je suis désolé que vous ayez des  problèmes, et je tiens à m'assurer qu'ils sont communiqués aux  meilleures personnes qui peuvent vous aider. Il y a plusieurs options  disponibles pour fournir le meilleur niveau de support :- Poster sur  les forums [Configuration Manager forums]  (https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB).  Celles-ci sont dirigées par des MVP (personnes de valeur) de notre  communauté qui sont très qualifiés, bien informés et très utiles.-  Utiliser [Microsoft Support] (https://aka.ms/cmcbsupport) pour  rechercher le problème ou ouvrir un dossier avec un support  professionnel.- Contacter votre équipe Microsoft Premier, par exemple un ingénieur de terrain ou un responsable de compte technique.Je ferme ce numéro parce qu'il n'y a rien qui puisse donner lieu à une action pour les docs en ce moment.
-- | --
