### ISSUE TITLE
script rewrite

### ISSUE THREAD

**Issue by michel-priori** [MicrosoftDocs/SCCMDocs.fr-fr#6]
SET NOCOUNT ON
DECLARE @dbname NVARCHAR(128) = db_name(DB_ID());
DECLARE @msg nvarchar(max) = 'ERROR: Script is targetting a ' + @dbname +' system database. It should be targeting "user" database.';
Declare @result Table
	(parametre			nvarchar(256)
	,current_value		nvarchar(256)
	,needed_value		nvarchar(256)
	,remediation_script	NVARCHAR(max)
	);

IF (db_id()&lt;5 OR @dbname = N'distribution' ) 
	BEGIN
		RAISERROR(@msg, 0, 1)
		GOTO Branch_Exit;
	END 

	/* Debut des vérifications */

Insert into @result(parametre,current_value,needed_value,remediation_script)
	select 'clr enabled', cast(c.value_in_use as nvarchar(256)), 1
		,'sp_configure ''show advanced options'', 1; GO; RECONFIGURE; GO; sp_configure ''clr enabled'', 1; GO; RECONFIGURE; ' 
	FROM sys.configurations c 
	WHERE c.name = 'clr enabled' 
		AND c.value_in_use = 1

Insert into @result(parametre,current_value,needed_value,remediation_script)
	select 'max text repl size (B)', cast(c.value_in_use as nvarchar(256)),2147483647
		,'EXECUTE sp_configure ''max text repl size (B)'', 2147483647'  
	FROM sys.configurations c 
	WHERE c.name = 'max text repl size (B)' 
			AND c.value_in_use = 2147483647 

Insert into @result(parametre,current_value,needed_value,remediation_script)
	select 'Database Owner', User_name(db.owner_sid), user_name(0x01)
		,' use ' + @dbname + '; GO; EXEC sp_changedbowner ' + suser_sname(0x01)
		FROM sys.databases db 
		WHERE db.database_id = DB_ID() 
			AND db.owner_sid = 0x01

Insert into @result(parametre,current_value,needed_value,remediation_script)
	SELECT 'is_trustworthy_on',db.is_trustworthy_on , 1 
		,'ALTER DATABASE ' + @dbname + ' SET TRUSTWORTHY ON;'
	FROM sys.databases db 
	WHERE db.database_id = DB_ID() 
		AND db.is_trustworthy_on = 1 

Insert into @result(parametre,current_value,needed_value,remediation_script)
	SELECT  'is_broker_enabled', db.is_broker_enabled , 1 
		,'ALTER DATABASE ' + @dbname + ' SET ENABLE_BROKER'
	FROM sys.databases db 
	WHERE db.database_id = DB_ID() 
		AND db.is_broker_enabled = 1 

Insert into @result(parametre,current_value,needed_value,remediation_script)
	SELECT 'is_honor_broker_priority_on', db.is_honor_broker_priority_on , 1 
		,'ALTER DATABASE ' + @dbname + ' SET HONOR_BROKER_PRIORITY ON; ALTER DATABASE ' + @dbname + ' SET ENABLE_BROKER WITH ROLLBACK IMMEDIATE'
	FROM sys.databases db 
	WHERE db.database_id = DB_ID() 
		AND db.is_honor_broker_priority_on = 1 

select * from @result
Branch_Exit:

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 53d1da83-d988-fb2b-82c5-fd9cf117cd42
* Version Independent ID: 2b1a3bd2-5116-1f21-c196-e3e5698a83c9
* Content: [SQL Server AlwaysOn - Configuration Manager](https://docs.microsoft.com/fr-fr/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database)
* Content Source: [sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md](https://github.com/Microsoft/SCCMDocs.fr-fr/blob/live/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by srvbpigh** [comment]
Hello, @michel-priori
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @michel-priori 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by aczechowski** [comment]
Hi @CeciAc, I understand the intent of the feedback, just need to check with the engineering team to verify. Can you please migrate this to the main SCCMDocs repo and I'll triage and followup

**Comment by CeciAc** [comment]
Hello, @michel-priori @aczechowski 

Please review the status of the issue here - https://github.com/MicrosoftDocs/SCCMdocs/issues/1964

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
